name: my_money_diary
description: YumNumm's Money Diary Application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.6.8
  email_validator: ^2.1.17
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_appauth:
    git:
      url: https://github.com/oliverbytes/flutter_appauth.git
      path: flutter_appauth
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  hooks_riverpod: ^2.4.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.1
  supabase_flutter: ^1.10.23

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.4.0
  envied_generator: ^0.3.0+3
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.2.4
  json_serializable: ^6.7.1
  pedantic_mono: ^1.23.0
  riverpod_generator: ^2.2.4
  riverpod_lint: ^1.4.0

flutter:
  uses-material-design: true
